GARNAME = readline
GARVERSION = 4.3
MASTER_SITES = ftp://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

BOOKS = \
	$(WORKSRC)/doc/rlman.texinfo \
	$(WORKSRC)/doc/rluserman.texinfo \
	$(WORKSRC)/doc/hist.texinfo

include ../../gar.mk
