GARNAME = bash
GARVERSION = 2.05b
MASTER_SITES = ftp://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

BOOKS = $(WORKSRC)/doc/bashref.texi

include ../../gar.mk

MAKEINFO_FLAGS += -I ../lib/readline/doc
