#!/bin/sh
# Copyright (C) 2002, Earnie Boyd <earnie@users.sf.net>
# This file is a part of msysDVLPR
#   http://www.mingw.org/msysdvlpr.shtml
#
# File: msysrlsbld
# Desc: Build a package for MSYS release.
# Vers: 1.1
# LMDt: 2002.04.17

# ccflags can be set external to control use of new flags without needing to
# change this file. E.G.: ccflags='-O0 -g -fnative-struct -fgnu-linker'.
if [ -z "$ccflags" ]
then
  ccflags='-O2 -s -fnative-struct -fgnu-linker -finline-functions'
fi

# You can set msysinstalldir so that the build installs to the project store
# directory.  E.G.: export msysinstalldir=/prj/msys/nstl.
if [ -z $msysinstalldir ]
then
  msysinstalldir=`pwd`/nstl
fi

make clean
make CFLAGS="$ccflags -mcpu=pentium" CXXFLAGS="$ccflags -mcpu=pentium"
make install prefix=$msysinstalldir/pkg
exit

#TODO:
# Add package options for configuring and building the release
# Add release management routines.
