GARNAME = grep
GARVERSION = 2.5.1
MASTER_SITES = ftp://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/doc/Makefile

BOOKS = $(WORKSRC)/doc/grep.texi

include ../../gar.mk
