GARNAME = texinfo
GARVERSION = 4.5
MASTER_SITES = ftp://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

BOOKS = $(WORKSRC)/doc/texinfo.txi $(WORKSRC)/doc/info.texi

include ../../gar.mk
