#ifndef ACTION_H_INC
#define ACTION_H_INC


#define ACT_NO_CHANGE 0
#define ACT_INSTALL_VERSION 1
#define ACT_REMOVE 2
#define ACT_REINSTALL 3

#define PSTATUS_STABLE 0
#define PSTATUS_ALPHA 1


#endif // ACTION_H_INC
