
#ifndef IDC_STATIC
#	define IDC_STATIC -1
#endif


#define SASHWND_VERT_CLASSNAME "wcMGSashWndVert"
#define SASHWND_HORZ_CLASSNAME "wcMGSashWndHorz"


#define IDD_MAINDLG 101
#define IDD_INSTSEL 102

#define IDC_CATLIST 201
#define IDC_COMPLIST 202
#define IDC_CATTYPE 203
#define IDC_MAINTOOLBAR 204
#define IDC_STATBAR 205
#define IDC_FULLDESC 206
#define IDC_EXISTMANAGE 207
#define IDC_INSTPATH 208
#define IDC_BROWSENEWINST 209
#define IDC_PREVINSTLIST 210
#define IDC_VALTEXT 211
#define IDC_DESCTITLE 212
#define IDC_INSTVERSION 213
#define IDC_VTITEXT 214
#define IDC_VERTSASH 215
#define IDC_HORZSASH 216

#define IDA_MAINACCEL 301

#define IDB_TBBUTTONS 401
#define IDB_STATES 402

#define IDM_MAINMENU 1101

#define IDM_FILE_EXIT 1201
#define IDM_FILE_CHANGEINST 1202
#define IDM_EDIT_PREFERENCES 1203
#define IDM_SOURCES_UPDATELISTS 1204
#define IDM_SOURCES_MIRRORS 1205
