/* Automatically generated by po2tbl.sed from tar.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"invalid argument %s for `%s'", 2},
  {"ambiguous argument %s for `%s'", 3},
  {"Valid arguments are:", 4},
  {"Unknown system error", 5},
  {"%s: option `%s' is ambiguous\n", 6},
  {"%s: option `--%s' doesn't allow an argument\n", 7},
  {"%s: option `%c%s' doesn't allow an argument\n", 8},
  {"%s: option `%s' requires an argument\n", 9},
  {"%s: unrecognized option `--%s'\n", 10},
  {"%s: unrecognized option `%c%s'\n", 11},
  {"%s: illegal option -- %c\n", 12},
  {"%s: invalid option -- %c\n", 13},
  {"%s: option requires an argument -- %c\n", 14},
  {"%s: option `-W %s' is ambiguous\n", 15},
  {"%s: option `-W %s' doesn't allow an argument\n", 16},
  {"block size", 17},
  {"`", 18},
  {"'", 19},
  {"memory exhausted", 20},
  {"Total bytes written: %s (%sB, %sB/s)\n", 21},
  {"(pipe)", 22},
  {"Cannot close", 23},
  {"Cannot dup", 24},
  {"Cannot use compressed or remote archives", 25},
  {"tar (child)", 26},
  {"tar (grandchild)", 27},
  {"Invalid value for record_size", 28},
  {"No archive name given", 29},
  {"Cannot verify multi-volume archives", 30},
  {"Cannot allocate memory for blocking factor %d", 31},
  {"Cannot use multi-volume compressed archives", 32},
  {"Cannot verify compressed archives", 33},
  {"Cannot update compressed archives", 34},
  {"Cannot verify stdin/stdout archive", 35},
  {"Archive not labeled to match %s", 36},
  {"Volume %s does not match %s", 37},
  {"Write checkpoint %d", 38},
  {"At beginning of tape, quitting now", 39},
  {"Too many errors, quitting", 40},
  {"Read checkpoint %d", 41},
  {"Reading %s\n", 42},
  {"WARNING: No volume header", 43},
  {"%s is not continued on this volume", 44},
  {"%s is the wrong size (%s != %s + %s)", 45},
  {"This volume is out of sequence", 46},
  {"%d garbage bytes ignored at end of archive", 47},
  {"Unaligned block (%lu bytes) in archive", 48},
  {"Record size = %lu blocks", 49},
  {"Cannot backspace archive file; it may be unreadable without -i", 50},
  {"Child died with signal %d", 51},
  {"Child returned status %d", 52},
  {"%s: contains invalid volume number", 53},
  {"Volume number overflow", 54},
  {"Prepare volume #%d for %s and hit return: ", 55},
  {"EOF where user reply was expected", 56},
  {"WARNING: Archive is incomplete", 57},
  {"\
 n [name]   Give a new file name for the next (and subsequent) volume(s)\n\
 q          Abort tar\n\
 !          Spawn a subshell\n\
 ?          Print this list\n", 58},
  {"No new volume; exiting.\n", 59},
  {"Could only read %lu of %lu bytes", 60},
  {"Contents differ", 61},
  {"Unexpected EOF in archive", 62},
  {"Verify ", 63},
  {"%s: Unknown file type '%c', diffed as normal file", 64},
  {"File type differs", 65},
  {"Mode differs", 66},
  {"Uid differs", 67},
  {"Gid differs", 68},
  {"Mod time differs", 69},
  {"Size differs", 70},
  {"Not linked to %s", 71},
  {"Symlink differs", 72},
  {"Device number differs", 73},
  {"VERIFY FAILURE: %d invalid header(s) detected", 74},
  {"Generating negative octal headers", 75},
  {"value %s out of %s range %s..%s; substituting %s", 76},
  {"value %s out of %s range %s..%s", 77},
  {"Member names contain `..'", 78},
  {"Removing leading `%.*s' from member names", 79},
  {"%s: file is unchanged; not dumped", 80},
  {"%s: file is the archive; not dumped", 81},
  {"%s: file is on a different filesystem; not dumped", 82},
  {"%s: File removed before we read it", 83},
  {"%s: File shrank by %s bytes; padding with zeros", 84},
  {"%s: file changed as we read it", 85},
  {"%s: socket ignored", 86},
  {"%s: door ignored", 87},
  {"%s: Unknown file type; file ignored", 88},
  {"This does not look like a tar archive", 89},
  {"Skipping to next header", 90},
  {"Deleting non-header from archive", 91},
  {"%s: time stamp %s is %lu s in the future", 92},
  {"%s: Unexpected inconsistency when making directory", 93},
  {"%s: Member name contains `..'", 94},
  {"%s: Was unable to backup this file", 95},
  {"Extracting contiguous files as regular files", 96},
  {"Attempting extraction of symbolic links as hard links", 97},
  {"%s: Cannot link to %s", 98},
  {"%s: Cannot extract -- file is continued from another volume", 99},
  {"Visible long name error", 100},
  {"%s: Unknown file type '%c', extracted as normal file", 101},
  {"Error is not recoverable: exiting now", 102},
  {"%s: Directory has been renamed", 103},
  {"%s: Directory is new", 104},
  {"Invalid time stamp", 105},
  {"Time stamp out of range", 106},
  {"Invalid device number", 107},
  {"Device number out of range", 108},
  {"Invalid inode number", 109},
  {"Inode number out of range", 110},
  {"%s: Deleting %s\n", 111},
  {"%s: Cannot remove", 112},
  {"%s: Omitting", 113},
  {"block %s: ** Block of NULs **\n", 114},
  {"block %s: ** End of File **\n", 115},
  {"Blanks in header where numeric %s value expected", 116},
  {"Archive octal value %.*s is out of %s range; assuming two's complement", 117},
  {"Archive octal value %.*s is out of %s range", 118},
  {"Archive contains obsolescent base-64 headers", 119},
  {"Archive signed base-64 string %s is out of %s range", 120},
  {"Archive base-256 value is out of %s range", 121},
  {"Archive contains %.*s where numeric %s value expected", 122},
  {"Archive value %s is out of %s range %s..%s", 123},
  {"block %s: ", 124},
  {"Visible longname error", 125},
  {" link to %s\n", 126},
  {" unknown file type %s\n", 127},
  {"--Volume Header--\n", 128},
  {"--Continued at byte %s--\n", 129},
  {"--Mangled file names--\n", 130},
  {"Creating directory:", 131},
  {"Unexpected EOF in mangled names", 132},
  {"%s: Cannot rename to %s", 133},
  {"Renamed %s to %s", 134},
  {"%s: Cannot symlink to %s", 135},
  {"Symlinked %s to %s", 136},
  {"Unknown demangling command %s", 137},
  {"Renaming %s to %s\n", 138},
  {"Renaming %s back to %s\n", 139},
  {"Cannot save working directory", 140},
  {"Cannot change working directory", 141},
  {"%s: Cannot %s", 142},
  {"%s: Warning: Cannot %s", 143},
  {"%s: Cannot change mode to %s", 144},
  {"%s: Cannot change ownership to uid %lu, gid %lu", 145},
  {"%s: Read error at byte %s, reading %lu bytes", 146},
  {"%s: Warning: Read error at byte %s, reading %lu bytes", 147},
  {"%s: Cannot seek to %s", 148},
  {"%s: Warning: Cannot seek to %s", 149},
  {"%s: Cannot create symlink to %s", 150},
  {"%s: Wrote only %lu of %lu bytes", 151},
  {"child process", 152},
  {"interprocess channel", 153},
  {"Missing file name after -C", 154},
  {"%s: Not found in archive", 155},
  {"rmtd: Cannot allocate buffer space\n", 156},
  {"Cannot allocate buffer space", 157},
  {"Try `%s --help' for more information.\n", 158},
  {"\
Usage: %s [OPTION]\n\
Manipulate a tape drive, accepting commands from a remote process.\n\
\n\
  --version  Output version info.\n\
  --help  Output this help.\n", 159},
  {"\
\n\
Report bugs to <bug-tar@gnu.org>.\n", 160},
  {"\
This program comes with NO WARRANTY, to the extent permitted by law.\n\
You may redistribute it under the terms of the GNU General Public License;\n\
see the file named COPYING for details.", 161},
  {"Seek offset out of range", 162},
  {"Seek direction out of range", 163},
  {"rmtd: Premature eof\n", 164},
  {"Premature end of file", 165},
  {"rmtd: Garbage command %c\n", 166},
  {"Garbage command", 167},
  {"exec/tcp: Service not available", 168},
  {"stdin", 169},
  {"stdout", 170},
  {"Cannot execute remote shell", 171},
  {"Options `-%s' and `-%s' both want standard input", 172},
  {"\
GNU `tar' saves many files together into a single tape or disk archive, and\n\
can restore individual files from the archive.\n", 173},
  {"\
\n\
Usage: %s [OPTION]... [FILE]...\n\
\n\
Examples:\n\
  %s -cf archive.tar foo bar  # Create archive.tar from files foo and bar.\n\
  %s -tvf archive.tar         # List all files in archive.tar verbosely.\n\
  %s -xf archive.tar          # Extract all files from archive.tar.\n", 174},
  {"\
\n\
If a long option shows an argument as mandatory, then it is mandatory\n\
for the equivalent short option also.  Similarly for optional arguments.\n", 175},
  {"\
\n\
Main operation mode:\n\
  -t, --list              list the contents of an archive\n\
  -x, --extract, --get    extract files from an archive\n\
  -c, --create            create a new archive\n\
  -d, --diff, --compare   find differences between archive and file system\n\
  -r, --append            append files to the end of an archive\n\
  -u, --update            only append files newer than copy in archive\n\
  -A, --catenate          append tar files to an archive\n\
      --concatenate       same as -A\n\
      --delete            delete from the archive (not on mag tapes!)\n", 176},
  {"\
\n\
Operation modifiers:\n\
  -W, --verify               attempt to verify the archive after writing it\n\
      --remove-files         remove files after adding them to the archive\n\
  -k, --keep-old-files       don't replace existing files when extracting\n\
      --overwrite            overwrite existing files when extracting\n\
  -U, --unlink-first         remove each file prior to extracting over it\n\
      --recursive-unlink     empty hierarchies prior to extracting \
directory\n\
  -S, --sparse               handle sparse files efficiently\n\
  -O, --to-stdout            extract files to standard output\n\
  -G, --incremental          handle old GNU-format incremental backup\n\
  -g, --listed-incremental=FILE\n\
                             handle new GNU-format incremental backup\n\
      --ignore-failed-read   do not exit with nonzero on unreadable files\n", 177},
  {"\
\n\
Handling of file attributes:\n\
      --owner=NAME             force NAME as owner for added files\n\
      --group=NAME             force NAME as group for added files\n\
      --mode=CHANGES           force (symbolic) mode CHANGES for added \
files\n\
      --atime-preserve         don't change access times on dumped files\n\
  -m, --modification-time      don't extract file modified time\n\
      --same-owner             try extracting files with the same ownership\n\
      --no-same-owner          extract files as yourself\n\
      --numeric-owner          always use numbers for user/group names\n\
  -p, --same-permissions       extract permissions information\n\
      --no-same-permissions    do not extract permissions information\n\
      --preserve-permissions   same as -p\n\
  -s, --same-order             sort names to extract to match archive\n\
      --preserve-order         same as -s\n\
      --preserve               same as both -p and -s\n", 178},
  {"\
\n\
Device selection and switching:\n\
  -f, --file=ARCHIVE             use archive file or device ARCHIVE\n\
      --force-local              archive file is local even if has a colon\n\
      --rsh-command=COMMAND      use remote COMMAND instead of rsh\n\
  -[0-7][lmh]                    specify drive and density\n\
  -M, --multi-volume             create/list/extract multi-volume archive\n\
  -L, --tape-length=NUM          change tape after writing NUM x 1024 bytes\n\
  -F, --info-script=FILE         run script at end of each tape (implies \
-M)\n\
      --new-volume-script=FILE   same as -F FILE\n\
      --volno-file=FILE          use/update the volume number in FILE\n", 179},
  {"\
\n\
Device blocking:\n\
  -b, --blocking-factor=BLOCKS   BLOCKS x 512 bytes per record\n\
      --record-size=SIZE         SIZE bytes per record, multiple of 512\n\
  -i, --ignore-zeros             ignore zeroed blocks in archive (means \
EOF)\n\
  -B, --read-full-records        reblock as we read (for 4.2BSD pipes)\n", 180},
  {"\
\n\
Archive format selection:\n\
  -V, --label=NAME                   create archive with volume name NAME\n\
              PATTERN                at list/extract time, a globbing \
PATTERN\n\
  -o, --old-archive, --portability   write a V7 format archive\n\
      --posix                        write a POSIX format archive\n\
  -j, --bzip2                        filter the archive through bzip2\n\
  -z, --gzip, --ungzip               filter the archive through gzip\n\
  -Z, --compress, --uncompress       filter the archive through compress\n\
      --use-compress-program=PROG    filter through PROG (must accept -d)\n", 181},
  {"\
\n\
Local file selection:\n\
  -C, --directory=DIR          change to directory DIR\n\
  -T, --files-from=NAME        get names to extract or create from file \
NAME\n\
      --null                   -T reads null-terminated names, disable -C\n\
      --exclude=PATTERN        exclude files, given as a globbing PATTERN\n\
  -X, --exclude-from=FILE      exclude globbing patterns listed in FILE\n\
  -P, --absolute-names         don't strip leading `/'s from file names\n\
  -h, --dereference            dump instead the files symlinks point to\n\
      --no-recursion           avoid descending automatically in \
directories\n\
  -l, --one-file-system        stay in local file system when creating \
archive\n\
  -K, --starting-file=NAME     begin at file NAME in the archive\n", 182},
  {"\
  -N, --newer=DATE             only store files newer than DATE\n\
      --newer-mtime            compare date and time when data changed only\n\
      --after-date=DATE        same as -N\n", 183},
  {"\
      --backup[=CONTROL]       backup before removal, choose version \
control\n\
      --suffix=SUFFIX          backup before removal, override usual suffix\n", 184},
  {"\
\n\
Informative output:\n\
      --help            print this help, then exit\n\
      --version         print tar program version number, then exit\n\
  -v, --verbose         verbosely list files processed\n\
      --checkpoint      print directory names while reading the archive\n\
      --totals          print total bytes written while creating archive\n\
  -R, --block-number    show block number within archive with each message\n\
  -w, --interactive     ask for confirmation for every action\n\
      --confirmation    same as -w\n", 185},
  {"\
\n\
The backup suffix is `~', unless set with --suffix or SIMPLE_BACKUP_SUFFIX.\n\
The version control may be set with --backup or VERSION_CONTROL, values \
are:\n\
\n\
  t, numbered     make numbered backups\n\
  nil, existing   numbered if numbered backups exist, simple otherwise\n\
  never, simple   always make simple backups\n", 186},
  {"\
\n\
GNU tar cannot read nor produce `--posix' archives.  If POSIXLY_CORRECT\n\
is set in the environment, GNU extensions are disallowed with `--posix'.\n\
Support for POSIX is only partially implemented, don't count on it yet.\n\
ARCHIVE may be FILE, HOST:FILE or USER@HOST:FILE; and FILE may be a file\n\
or a device.  *This* `tar' defaults to `-f%s -b%d'.\n", 187},
  {"You may not specify more than one `-Acdtrux' option", 188},
  {"Conflicting compression options", 189},
  {"Old option `%c' requires an argument.", 190},
  {"Obsolete option, now implied by --blocking-factor", 191},
  {"Obsolete option name replaced by --blocking-factor", 192},
  {"Invalid blocking factor", 193},
  {"Obsolete option name replaced by --read-full-records", 194},
  {"Invalid tape length", 195},
  {"Obsolete option name replaced by --touch", 196},
  {"More than one threshold date", 197},
  {"Date file not found", 198},
  {"Substituting %s for unknown date format %s", 199},
  {"Conflicting archive format options", 200},
  {"Obsolete option name replaced by --absolute-names", 201},
  {"Obsolete option name replaced by --block-number", 202},
  {"Obsolete option name replaced by --backup", 203},
  {"%s: Invalid group", 204},
  {"Invalid mode given on option", 205},
  {"Invalid owner", 206},
  {"Invalid record size", 207},
  {"Record size must be a multiple of %d.", 208},
  {"Options `-[0-7][lmh]' not supported by *this* tar", 209},
  {"Written by John Gilmore and Jay Fenlason.", 210},
  {"GNU features wanted on incompatible archive format", 211},
  {"Multiple archive files requires `-M' option", 212},
  {"Cannot combine --listed-incremental with --newer", 213},
  {"%s: Volume label is too long (limit is %lu bytes)", 214},
  {"Cowardly refusing to create an empty archive", 215},
  {"Options `-Aru' are incompatible with `-f -'", 216},
  {"You must specify one of the `-Acdtrux' options", 217},
  {"Error in writing to standard output", 218},
  {"Error exit delayed from previous errors", 219},
  {"%s: File shrank by %s bytes", 220},
  {"Generate data files for GNU tar test suite.\n", 221},
  {"\
\n\
Usage: %s [OPTION]...\n", 222},
  {"\
If a long option shows an argument as mandatory, then it is mandatory\n\
for the equivalent short option also.\n\
\n\
  -l, --file-length=LENGTH   LENGTH of generated file\n\
  -p, --pattern=PATTERN      PATTERN is `default' or `zeros'\n\
      --help                 display this help and exit\n\
      --version              output version information and exit\n", 223},
  {"Ambiguous pattern `%s'", 224},
  {"Unknown pattern `%s'", 225},
  {"\
\n\
Copyright (C) 1995, 1996, 1997 Free Software Foundation, Inc.\n", 226},
  {"\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n", 227},
  {"\
\n\
Written by François Pinard <pinard@iro.umontreal.ca>.\n", 228},
};

int _msg_tbl_length = 228;
