/* Automatically generated by po2tbl.sed from textutils.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Try `%s --help' for more information.\n", 2},
  {"Usage: %s [OPTION] [FILE]...\n", 3},
  {"\
Concatenate FILE(s), or standard input, to standard output.\n\
\n\
  -A, --show-all           equivalent to -vET\n\
  -b, --number-nonblank    number nonblank output lines\n\
  -e                       equivalent to -vE\n\
  -E, --show-ends          display $ at end of each line\n\
  -n, --number             number all output lines\n\
  -s, --squeeze-blank      never more than one single blank line\n\
  -t                       equivalent to -vT\n\
  -T, --show-tabs          display TAB characters as ^I\n\
  -u                       (ignored)\n\
  -v, --show-nonprinting   use ^ and M- notation, except for LFD and TAB\n\
      --help               display this help and exit\n\
      --version            output version information and exit\n\
\n\
With no FILE, or when FILE is -, read standard input.\n", 4},
  {"\
\n\
  -B, --binary             use binary writes to the console device.\n\
\n", 5},
  {"\
\n\
Report bugs to <bug-textutils@gnu.org>.", 6},
  {"write error", 7},
  {"cannot do ioctl on `%s'", 8},
  {"standard output", 9},
  {"%s: input file is output file", 10},
  {"Usage: %s [OPTION]... [FILE]...\n", 11},
  {"\
Print CRC checksum and byte counts of each FILE.\n\
\n\
  --help      display this help and exit\n\
  --version   output version information and exit\n", 12},
  {"Usage: %s [OPTION]... LEFT_FILE RIGHT_FILE\n", 13},
  {"\
Compare sorted files LEFT_FILE and RIGHT_FILE line by line.\n\
\n\
  -1              suppress lines unique to left file\n\
  -2              suppress lines unique to right file\n\
  -3              suppress lines unique to both files\n\
      --help      display this help and exit\n\
      --version   output version information and exit\n", 14},
  {"read error", 15},
  {"input disappeared", 16},
  {"%s: line number out of range", 17},
  {"%s: `%s': line number out of range", 18},
  {" on repetition %d\n", 19},
  {"%s: `%s': match not found", 20},
  {"error in regular expression search", 21},
  {"write error for `%s'", 22},
  {"%s: `+' or `-' expected after delimeter", 23},
  {"%s: integer expected after `%c'", 24},
  {"%s: `}' is required in repeat count", 25},
  {"%s}: integer required between `{' and `}'", 26},
  {"%s: closing delimeter `%c' missing", 27},
  {"%s: invalid regular expression: %s", 28},
  {"%s: invalid pattern", 29},
  {"%s: line number must be greater than zero", 30},
  {"line number `%s' is smaller than preceding line number, %s", 31},
  {"warning: line number `%s' is the same as preceding line number", 32},
  {"missing conversion specifier in suffix", 33},
  {"invalid conversion specifier in suffix: %c", 34},
  {"invalid conversion specifier in suffix: \\%.3o", 35},
  {"missing %% conversion specification in suffix", 36},
  {"too many %% conversion specifications in suffix", 37},
  {"%s: invalid number", 38},
  {"too few arguments", 39},
  {"Usage: %s [OPTION]... FILE PATTERN...\n", 40},
  {"\
Output pieces of FILE separated by PATTERN(s) to files `xx01', `xx02', ...,\n\
and output byte counts of each piece to standard output.\n\
\n\
  -b, --suffix-format=FORMAT use sprintf FORMAT instead of %%d\n\
  -f, --prefix=PREFIX        use PREFIX instead of `xx'\n\
  -k, --keep-files           do not remove output files on errors\n\
  -n, --digits=DIGITS        use specified number of digits instead of 2\n\
  -s, --quiet, --silent      do not print counts of output file sizes\n\
  -z, --elide-empty-files    remove empty output files\n\
      --help                 display this help and exit\n\
      --version              output version information and exit\n\
\n\
Read standard input if FILE is -.  Each PATTERN may be:\n\
\n\
  INTEGER            copy up to but not including specified line number\n\
  /REGEXP/[OFFSET]   copy up to but not including a matching line\n\
  %%REGEXP%%[OFFSET]   skip to, but not including a matching line\n\
  {INTEGER}          repeat the previous pattern specified number of times\n\
  {*}                repeat the previous pattern as many times as possible\n\
\n\
A line OFFSET is a required `+' or `-' followed by a positive integer.\n", 41},
  {"\
Print selected parts of lines from each FILE to standard output.\n\
\n\
  -b, --bytes=LIST        output only these bytes\n\
  -c, --characters=LIST   output only these characters\n\
  -d, --delimiter=DELIM   use DELIM instead of TAB for field delimiter\n\
  -f, --fields=LIST       output only these fields\n\
  -n                      (ignored)\n\
  -s, --only-delimited    do not print lines not containing delimiters\n\
      --output-delimiter=STRING  use STRING as the output delimiter\n\
                            the default is to use the input delimiter\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n\
\n\
Use one, and only one of -b, -c or -f.  Each LIST is made up of one\n\
range, or many ranges separated by commas.  Each range is one of:\n\
\n\
  N     N'th byte, character or field, counted from 1\n\
  N-    from N'th byte, character or field, to end of line\n\
  N-M   from N'th to M'th (included) byte, character or field\n\
  -M    from first to M'th (included) byte, character or field\n\
\n\
With no FILE, or when FILE is -, read standard input.\n", 42},
  {"invalid byte or field list", 43},
  {"only one type of list may be specified", 44},
  {"missing list of positions", 45},
  {"missing list of fields", 46},
  {"the delimiter must be a single character", 47},
  {"you must specify a list of bytes, characters, or fields", 48},
  {"a delimiter may be specified only when operating on fields", 49},
  {"\
suppressing non-delimited lines makes sense\n\
\tonly when operating on fields", 50},
  {"\
Convert tabs in each FILE to spaces, writing to standard output.\n\
With no FILE, or when FILE is -, read standard input.\n\
\n\
  -i, --initial       do not convert TABs after non whitespace\n\
  -t, --tabs=NUMBER   have tabs NUMBER characters apart, not 8\n\
  -t, --tabs=LIST     use comma separated list of explicit tab positions\n\
      --help          display this help and exit\n\
      --version       output version information and exit\n\
\n\
Instead of -t NUMBER or -t LIST, -NUMBER or -LIST may be used.\n", 51},
  {"tab size contains an invalid character", 52},
  {"tab size cannot be 0", 53},
  {"tab sizes must be ascending", 54},
  {"Usage: %s [-DIGITS] [OPTION]... [FILE]...\n", 55},
  {"\
Reformat each paragraph in the FILE(s), writing to standard output.\n\
If no FILE or if FILE is `-', read standard input.\n\
\n\
Mandatory arguments to long options are mandatory for short options too.\n\
  -c, --crown-margin        preserve indentation of first two lines\n\
  -p, --prefix=STRING       combine only lines having STRING as prefix\n\
  -s, --split-only          split long lines, but do not refill\n\
  -t, --tagged-paragraph    indentation of first line different from second\n\
  -u, --uniform-spacing     one space between words, two after sentences\n\
  -w, --width=NUMBER        maximum line width (default of 75 columns)\n\
      --help                display this help and exit\n\
      --version             output version information and exit\n\
\n\
In -wNUMBER, the letter `w' may be omitted.\n", 56},
  {"invalid line number increment: `%s'", 57},
  {"\
Wrap input lines in each FILE (standard input by default), writing to\n\
standard output.\n\
\n\
  -b, --bytes         count bytes rather than columns\n\
  -s, --spaces        break at spaces\n\
  -w, --width=WIDTH   use WIDTH columns instead of 80\n\
      --help          display this help and exit\n\
      --version       output version information and exit\n", 58},
  {"invalid number of columns: `%s'", 59},
  {"\
Print first 10 lines of each FILE to standard output.\n\
With more than one FILE, precede each with a header giving the file name.\n\
With no FILE, or when FILE is -, read standard input.\n\
\n\
  -c, --bytes=SIZE         print first SIZE bytes\n\
  -n, --lines=NUMBER       print first NUMBER lines instead of first 10\n\
  -q, --quiet, --silent    never print headers giving file names\n\
  -v, --verbose            always print headers giving file names\n\
      --help               display this help and exit\n\
      --version            output version information and exit\n\
\n\
SIZE may have a multiplier suffix: b for 512, k for 1K, m for 1 Meg.\n\
If -VALUE is used as first OPTION, read -c VALUE when one of\n\
multipliers bkm follows concatenated, else read -n VALUE.\n", 60},
  {"standard input", 61},
  {"invalid number of lines", 62},
  {"invalid number of bytes", 63},
  {"%s: %s is so large that it is not representable", 64},
  {"number of lines", 65},
  {"number of bytes", 66},
  {"unrecognized option `-%c'", 67},
  {"Usage: %s [OPTION]... FILE1 FILE2\n", 68},
  {"\
For each pair of input lines with identical join fields, write a line to\n\
standard output.  The default join field is the first, delimited\n\
by whitespace.  When FILE1 or FILE2 (not both) is -, read standard input.\n\
\n\
  -a SIDE           print unpairable lines coming from file SIDE\n\
  -e EMPTY          replace missing input fields with EMPTY\n\
  -i, --ignore-case ignore differences in case when comparing fields\n\
  -j FIELD          (obsolescent) equivalent to `-1 FIELD -2 FIELD'\n\
  -j1 FIELD         (obsolescent) equivalent to `-1 FIELD'\n\
  -j2 FIELD         (obsolescent) equivalent to `-2 FIELD'\n\
  -o FORMAT         obey FORMAT while constructing output line\n\
  -t CHAR           use CHAR as input and output field separator\n\
  -v SIDE           like -a SIDE, but suppress joined output lines\n\
  -1 FIELD          join on this FIELD of file 1\n\
  -2 FIELD          join on this FIELD of file 2\n\
      --help        display this help and exit\n\
      --version     output version information and exit\n\
\n\
Unless -t CHAR is given, leading blanks separate fields and are ignored,\n\
else fields are separated by CHAR.  Any FIELD is a field number counted\n\
from 1.  FORMAT is one or more comma or blank separated specifications,\n\
each being `SIDE.FIELD' or `0'.  Default FORMAT outputs the join field,\n\
the remaining fields from FILE1, the remaining fields from FILE2, all\n\
separated by CHAR.\n", 69},
  {"invalid field specifier: `%s'", 70},
  {"invalid field number: `%s'", 71},
  {"invalid file number in field spec: `%s'", 72},
  {"invalid field number for file 1: `%s'", 73},
  {"invalid field number for file 2: `%s'", 74},
  {"too many non-option arguments", 75},
  {"too few non-option arguments", 76},
  {"both files cannot be standard input", 77},
  {"\
Usage: %s [OPTION] [FILE]...\n\
  or:  %s [OPTION] --check [FILE]\n\
Print or check MD5 checksums.\n\
With no FILE, or when FILE is -, read standard input.\n\
\n\
  -b, --binary            read files in binary mode (default on \
DOS/Windows)\n\
  -c, --check             check MD5 sums against given list\n\
  -t, --text              read files in text mode (default)\n\
\n\
The following two options are useful only when verifying checksums:\n\
      --status            don't output anything, status code shows success\n\
  -w, --warn              warn about improperly formated MD5 checksum lines\n\
\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n\
\n\
The sums are computed as described in RFC 1321.  When checking, the input\n\
should be a former output of this program.  The default mode is to print\n\
a line with checksum, a character indicating type (`*' for binary, ` ' for\n\
text), and name for each FILE.\n", 78},
  {"%s: %lu: improperly formatted MD5 checksum line", 79},
  {"%s: FAILED open or read\n", 80},
  {"FAILED", 81},
  {"OK", 82},
  {"%s: read error", 83},
  {"%s: no properly formatted MD5 checksum lines found", 84},
  {"WARNING: %d of %d listed %s could not be read\n", 85},
  {"file", 86},
  {"files", 87},
  {"WARNING: %d of %d computed %s did NOT match", 88},
  {"checksum", 89},
  {"checksums", 90},
  {"\
the --binary and --text options are meaningless when verifying checksums", 91},
  {"the --string and --check options are mutually exclusive", 92},
  {"the --status option is meaningful only when verifying checksums", 93},
  {"the --warn option is meaningful only when verifying checksums", 94},
  {"no files may be specified when using --string", 95},
  {"only one argument may be specified when using --check", 96},
  {"\
Write each FILE to standard output, with line numbers added.\n\
With no FILE, or when FILE is -, read standard input.\n\
\n\
  -b, --body-numbering=STYLE      use STYLE for numbering body lines\n\
  -d, --section-delimiter=CC      use CC for separating logical pages\n\
  -f, --footer-numbering=STYLE    use STYLE for numbering footer lines\n\
  -h, --header-numbering=STYLE    use STYLE for numbering header lines\n\
  -i, --page-increment=NUMBER     line number increment at each line\n\
  -l, --join-blank-lines=NUMBER   group of NUMBER empty lines counted as \
one\n\
  -n, --number-format=FORMAT      insert line numbers according to FORMAT\n\
  -p, --no-renumber               do not reset line numbers at logical \
pages\n\
  -s, --number-separator=STRING   add STRING after (possible) line number\n\
  -v, --first-page=NUMBER         first line number on each logical page\n\
  -w, --number-width=NUMBER       use NUMBER columns for line numbers\n\
      --help                      display this help and exit\n\
      --version                   output version information and exit\n\
\n\
By default, selects -v1 -i1 -l1 -sTAB -w6 -nrn -hn -bt -fn.  CC are\n\
two delimiter characters for separating logical pages, a missing\n\
second character implies :.  Type \\\\ for \\.  STYLE is one of:\n\
\n\
  a         number all lines\n\
  t         number only nonempty lines\n\
  n         number no lines\n\
  pREGEXP   number only lines that contain a match for REGEXP\n\
\n\
FORMAT is one of:\n\
\n\
  ln   left justified, no leading zeros\n\
  rn   right justified, no leading zeros\n\
  rz   right justified, leading zeros\n\
\n", 97},
  {"invalid starting line number: `%s'", 98},
  {"invalid number of blank lines: `%s'", 99},
  {"invalid line number field width: `%s'", 100},
  {"\
Usage: %s [OPTION]... [FILE]...\n\
  or:  %s --traditional [FILE] [[+]OFFSET [[+]LABEL]]\n", 101},
  {"\
Write an unambiguous representation, octal bytes by default, of FILE\n\
to standard output.  With no FILE, or when FILE is -, read standard input.\n\
\n\
  -A, --address-radix=RADIX   decide how file offsets are printed\n\
  -j, --skip-bytes=BYTES      skip BYTES input bytes first on each file\n\
  -N, --read-bytes=BYTES      limit dump to BYTES input bytes per file\n\
  -s, --strings[=BYTES]       output strings of at least BYTES graphic \
chars\n\
  -t, --format=TYPE           select output format or formats\n\
  -v, --output-duplicates     do not use * to mark line suppression\n\
  -w, --width[=BYTES]         output BYTES bytes per output line\n\
      --traditional           accept arguments in pre-POSIX form\n\
      --help                  display this help and exit\n\
      --version               output version information and exit\n\
\n\
Pre-POSIX format specifications may be intermixed, they accumulate:\n\
  -a   same as -t a,  select named characters\n\
  -b   same as -t oC, select octal bytes\n\
  -c   same as -t c,  select ASCII characters or backslash escapes\n\
  -d   same as -t u2, select unsigned decimal shorts\n\
  -f   same as -t fF, select floats\n\
  -h   same as -t x2, select hexadecimal shorts\n\
  -i   same as -t d2, select decimal shorts\n\
  -l   same as -t d4, select decimal longs\n\
  -o   same as -t o2, select octal shorts\n\
  -x   same as -t x2, select hexadecimal shorts\n", 102},
  {"\
\n\
For older syntax (second call format), OFFSET means -j OFFSET.  LABEL\n\
is the pseudo-address at first byte printed, incremented when dump is\n\
progressing.  For OFFSET and LABEL, a 0x or 0X prefix indicates\n\
hexadecimal, suffixes maybe . for octal and b multiply by 512.\n\
\n\
TYPE is made up of one or more of these specifications:\n\
\n\
  a          named character\n\
  c          ASCII character or backslash escape\n\
  d[SIZE]    signed decimal, SIZE bytes per integer\n\
  f[SIZE]    floating point, SIZE bytes per integer\n\
  o[SIZE]    octal, SIZE bytes per integer\n\
  u[SIZE]    unsigned decimal, SIZE bytes per integer\n\
  x[SIZE]    hexadecimal, SIZE bytes per integer\n\
\n\
SIZE is a number.  For TYPE in doux, SIZE may also be C for\n\
sizeof(char), S for sizeof(short), I for sizeof(int) or L for\n\
sizeof(long).  If TYPE is f, SIZE may also be F for sizeof(float), D\n\
for sizeof(double) or L for sizeof(long double).\n\
\n\
RADIX is d for decimal, o for octal, x for hexadecimal or n for none.\n\
BYTES is hexadecimal with 0x or 0X prefix, it is multiplied by 512\n\
with b suffix, by 1024 with k and by 1048576 with m.  Adding a z suffix to\n\
any type adds a display of printable characters to the end of each line\n\
of output.  -s without a number implies 3.  -w without a number implies 32.\n\
By default, od uses -A o -t d2 -w 16.\n", 103},
  {"invalid type string `%s'", 104},
  {"\
invalid type string `%s';\n\
this system doesn't provide a %lu-byte integral type", 105},
  {"\
invalid type string `%s';\n\
this system doesn't provide a %lu-byte floating point type", 106},
  {"invalid character `%c' in type string `%s'", 107},
  {"cannot skip past end of combined input", 108},
  {"old-style offset", 109},
  {"invalid output address radix `%c'; it must be one character from [doxn]", 110},
  {"skip argument", 111},
  {"limit argument", 112},
  {"\
specified number of bytes `%s' is larger than the maximum\n\
representable value of type `long'", 113},
  {"minimum string length", 114},
  {"width specification", 115},
  {"no type may be specified when dumping strings", 116},
  {"invalid second operand in compatibility mode `%s'", 117},
  {"in compatibility mode, the last two arguments must be offsets", 118},
  {"compatibility mode supports at most three arguments", 119},
  {"warning: invalid width %lu; using %d instead", 120},
  {"%d: fmt=\"%s\" width=%d\n", 121},
  {"standard input is closed", 122},
  {"\
Write lines consisting of the sequentially corresponding lines from\n\
each FILE, separated by TABs, to standard output.\n\
With no FILE, or when FILE is -, read standard input.\n\
\n\
  -d, --delimiters=LIST   reuse characters from LIST instead of TABs\n\
  -s, --serial            paste one file at a time instead of in parallel\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n\
\n", 123},
  {"`--pages' invalid range of page numbers: `%s'", 124},
  {"`--pages' invalid starting page number: `%s'", 125},
  {"`--pages' invalid ending page number: `%s'", 126},
  {"`--pages' starting page number is larger than ending page number", 127},
  {"`--pages=FIRST_PAGE[:LAST_PAGE]' missing argument", 128},
  {"`--columns=COLUMN' invalid number of columns: `%s'", 129},
  {"`-l PAGE_LENGTH' invalid number of lines: `%s'", 130},
  {"`-N NUMBER' invalid starting line number: `%s'", 131},
  {"`-o MARGIN' invalid line offset: `%s'", 132},
  {"`-w PAGE_WIDTH' invalid number of characters: `%s'", 133},
  {"`-W PAGE_WIDTH' invalid number of characters: `%s'", 134},
  {"Cannot specify number of columns when printing in parallel.", 135},
  {"Cannot specify both printing across and printing in parallel.", 136},
  {"`-%c' extra characters or invalid number in the argument: `%s'", 137},
  {"page width too narrow", 138},
  {"%s%*s%s%*sPage", 139},
  {"starting page number larger than total number of pages: `%d'", 140},
  {"\
Paginate or columnate FILE(s) for printing.\n\
\n\
  +FIRST_PAGE[:LAST_PAGE], --pages=FIRST_PAGE[:LAST_PAGE]\n\
                    begin [stop] printing with page FIRST_[LAST_]PAGE\n\
  -COLUMN, --columns=COLUMN\n\
                    produce COLUMN-column output and print columns down,\n\
                    unless -a is used. Balance number of lines in the\n\
                    columns on each page.\n\
  -a, --across      print columns across rather than down, used together\n\
                    with -COLUMN\n\
  -c, --show-control-chars\n\
                    use hat notation (^G) and octal backslash notation\n\
  -d, --double-space\n\
                    double space the output\n\
  -e[CHAR[WIDTH]], --expand-tabs[=CHAR[WIDTH]]\n\
                    expand input CHARs (TABs) to tab WIDTH (8)\n\
  -F, -f, --form-feed\n\
                    use form feeds instead of newlines to separate pages\n\
                    (by a 3-line page header with -F or a 5-line header\n\
                    and trailer without -F)\n", 141},
  {"\
  -h HEADER, --header=HEADER\n\
                    use a centered HEADER instead of filename in page \
header,\n\
                    with long headers left-hand-side truncation may occur,\n\
                    -h \"\" prints a blank line, don't use -h\"\"\n\
  -i[CHAR[WIDTH]], --output-tabs[=CHAR[WIDTH]]\n\
                    replace spaces with CHARs (TABs) to tab WIDTH (8)\n\
  -J, --join-lines  merge full lines, turns off -W line truncation, no \
column\n\
                    alignment, -S[STRING] sets separators\n\
  -l PAGE_LENGTH, --length=PAGE_LENGTH\n\
                    set the page length to PAGE_LENGTH (66) lines\n\
                    (default number of lines of text 56, and with -F 63)\n\
  -m, --merge       print all files in parallel, one in each column,\n\
                    truncate lines, but join lines of full length with -J\n\
  -n[SEP[DIGITS]], --number-lines[=SEP[DIGITS]]\n\
                    number lines, use DIGITS (5) digits, then SEP (TAB),\n\
                    default counting starts with 1st line of input file\n\
  -N NUMBER, --first-line-number=NUMBER\n\
                    start counting with NUMBER at 1st line of first\n\
                    page printed (see +FIRST_PAGE)\n\
  -o MARGIN, --indent=MARGIN\n\
                    offset each line with MARGIN (zero) spaces, do not\n\
                    affect -w or -W, MARGIN will be added to PAGE_WIDTH\n\
  -r, --no-file-warnings\n\
                    omit warning when a file cannot be opened\n", 142},
  {"\
  -s[CHAR],--separator[=CHAR]\n\
                    separate columns by a single character, default for \
CHAR\n\
                    is the <TAB> character without -w and 'no char' with -w\n\
                    -s[CHAR] turns off line truncation of all 3 column\n\
                    options (-COLUMN|-a -COLUMN|-m) except -w is set\n\
  -S[STRING], --sep-string[=STRING]\n\
                    separate columns by an optional STRING, don't use\n\
                    -S \"STRING\", -S only: No separator used (same as \
-S\"\"),\n\
                    without -S: Default separator <TAB> with -J and <space>\n\
                    otherwise (same as -S\" \"), no effect on column \
options\n\
  -t, --omit-header omit page headers and trailers\n\
  -T, --omit-pagination\n\
                    omit page headers and trailers, eliminate any \
pagination\n\
                    by form feeds set in input files\n\
  -v, --show-nonprinting\n\
                    use octal backslash notation\n\
  -w PAGE_WIDTH, --width=PAGE_WIDTH\n\
                    set page width to PAGE_WIDTH (72) characters for\n\
                    multiple text-column output only, -s[char] turns off \
(72)\n\
  -W PAGE_WIDTH, --page-width=PAGE_WIDTH\n\
                    set page width to PAGE_WIDTH (72) characters always,\n\
                    truncate lines, except -J option is set, no \
interference\n\
                    with -S or -s\n\
  --help            display this help and exit\n\
  --version         output version information and exit\n\
\n\
-T implied by -l nn when nn <= 10 or <= 3 with -F. With no FILE, or when\n\
FILE is -, read standard input.\n", 143},
  {"%s (for regexp `%s')", 144},
  {"\
Usage: %s [OPTION]... [INPUT]...   (without -G)\n\
  or:  %s -G [OPTION]... [INPUT [OUTPUT]]\n", 145},
  {"\
Mandatory arguments to long options are mandatory for short options too.\n\
\n\
  -A, --auto-reference           output automatically generated references\n\
  -C, --copyright                display Copyright and copying conditions\n\
  -G, --traditional              behave more like System V `ptx'\n\
  -F, --flag-truncation=STRING   use STRING for flagging line truncations\n\
  -M, --macro-name=STRING        macro name to use instead of `xx'\n\
  -O, --format=roff              generate output as roff directives\n\
  -R, --right-side-refs          put references at right, not counted in -w\n\
  -S, --sentence-regexp=REGEXP   for end of lines or end of sentences\n\
  -T, --format=tex               generate output as TeX directives\n\
  -W, --word-regexp=REGEXP       use REGEXP to match each keyword\n\
  -b, --break-file=FILE          word break characters in this FILE\n\
  -f, --ignore-case              fold lower case to upper case for sorting\n\
  -g, --gap-size=NUMBER          gap size in columns between output fields\n\
  -i, --ignore-file=FILE         read ignore word list from FILE\n\
  -o, --only-file=FILE           read only word list from this FILE\n\
  -r, --references               first field of each line is a reference\n\
  -t, --typeset-mode               - not implemented -\n\
  -w, --width=NUMBER             output width in columns, reference \
excluded\n\
      --help                     display this help and exit\n\
      --version                  output version information and exit\n\
\n\
With no FILE or if FILE is -, read Standard Input.  `-F /' by default.\n", 146},
  {"\
This program is free software; you can redistribute it and/or modify\n\
it under the terms of the GNU General Public License as published by\n\
the Free Software Foundation; either version 2, or (at your option)\n\
any later version.\n\
\n\
This program is distributed in the hope that it will be useful,\n\
but WITHOUT ANY WARRANTY; without even the implied warranty of\n\
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n\
GNU General Public License for more details.\n\
\n\
You should have received a copy of the GNU General Public License\n\
along with this program; if not, write to the Free Software Foundation,\n\
Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.\n", 147},
  {"\
Write sorted concatenation of all FILE(s) to standard output.\n\
\n\
  +POS1 [-POS2]    start a key at POS1, end it *before* POS2 (obsolescent)\n\
\t\t     field numbers and character offsets are numbered\n\
                     starting with zero (contrast with the -k option)\n\
  -b               ignore leading blanks in sort fields or keys\n\
  -c               check if given files already sorted, do not sort\n\
  -d               consider only [a-zA-Z0-9 ] characters in keys\n\
  -f               fold lower case to upper case characters in keys\n\
  -g               compare according to general numerical value, imply -b\n\
  -i               consider only [\\040-\\0176] characters in keys\n\
  -k POS1[,POS2]   start a key at POS1, end it *at* POS2\n\
\t\t     field numbers and character offsets are numbered\n\
                     starting with one (contrast with zero-based +POS form)\n\
  -m               merge already sorted files, do not sort\n\
  -M               compare (unknown) < `JAN' < ... < `DEC', imply -b\n\
  -n               compare according to string numerical value, imply -b\n\
  -o FILE          write result on FILE instead of standard output\n\
  -r               reverse the result of comparisons\n\
  -s               stabilize sort by disabling last resort comparison\n\
  -t SEP           use SEParator instead of non- to whitespace transition\n\
  -T DIRECTORY     use DIRECTORY for temporary files, not $TMPDIR or %s\n\
  -u               with -c, check for strict ordering;\n\
                   with -m, only output the first of an equal sequence\n\
  -z               end lines with 0 byte, not newline, for find -print0\n\
      --help       display this help and exit\n\
      --version    output version information and exit\n\
\n", 148},
  {"\
POS is F[.C][OPTS], where F is the field number and C the character \
position\n\
in the field, both counted from one with -k, from zero with the obsolescent\n\
form.  OPTS is made up of one or more of Mbdfinr; this effectively disables\n\
global -Mbdfinr settings for that key.  If no key is given, use the entire\n\
line as the key.  With no FILE, or when FILE is -, read standard input.\n", 149},
  {"flushing file", 150},
  {"error closing file", 151},
  {"%s: write error", 152},
  {"%s: %s:%d: disorder: ", 153},
  {"standard error", 154},
  {"invalid field specification `%s'", 155},
  {"\
when using the old-style +POS and -POS key specifiers,\n\
the +POS specifier must come first", 156},
  {"option `-k' requires an argument", 157},
  {"the starting field number argument to the `-k' option must be positive", 158},
  {"starting field spec has `.' but lacks following character offset", 159},
  {"\
starting field character offset argument to the `-k' option\n\
must be positive", 160},
  {"field specification has `,' but lacks following field spec", 161},
  {"ending field number argument to the `-k' option must be positive", 162},
  {"ending field spec has `.' but lacks following character offset", 163},
  {"option `-o' requires an argument", 164},
  {"option `-t' requires an argument", 165},
  {"option `-T' requires an argument", 166},
  {"%s: unrecognized option `-%c'\n", 167},
  {"Usage: %s [OPTION] [INPUT [PREFIX]]\n", 168},
  {"\
Output fixed-size pieces of INPUT to PREFIXaa, PREFIXab, ...; default\n\
PREFIX is `x'.  With no INPUT, or when INPUT is -, read standard input.\n\
\n\
  -b, --bytes=SIZE        put SIZE bytes per output file\n\
  -C, --line-bytes=SIZE   put at most SIZE bytes of lines per output file\n\
  -l, --lines=NUMBER      put NUMBER lines per output file\n\
  -NUMBER                 same as -l NUMBER\n\
      --verbose           print a diagnostic to standard error just\n\
                            before each output file is opened\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n\
\n\
SIZE may have a multiplier suffix: b for 512, k for 1K, m for 1 Meg.\n", 169},
  {"creating file `%s'\n", 170},
  {"cannot split in more than one way", 171},
  {"%s: invalid number of bytes", 172},
  {"%s: invalid number of lines", 173},
  {"invalid number", 174},
  {"too many arguments", 175},
  {"\
Print checksum and block counts for each FILE.\n\
\n\
  -r              defeat -s, use BSD sum algorithm, use 1K blocks\n\
  -s, --sysv      use System V sum algorithm, use 512 bytes blocks\n\
      --help      display this help and exit\n\
      --version   output version information and exit\n\
\n\
With no FILE, or when FILE is -, read standard input.\n", 176},
  {"\
Write each FILE to standard output, last line first.\n\
With no FILE, or when FILE is -, read standard input.\n\
\n\
  -b, --before             attach the separator before instead of after\n\
  -r, --regex              interpret the separator as a regular expression\n\
  -s, --separator=STRING   use STRING as the separator instead of newline\n\
      --help               display this help and exit\n\
      --version            output version information and exit\n", 177},
  {"stdin: read error", 178},
  {"separator cannot be empty", 179},
  {"\
Print the last %d lines of each FILE to standard output.\n\
With more than one FILE, precede each with a header giving the file name.\n\
With no FILE, or when FILE is -, read standard input.\n\
\n\
      --retry              keep trying to open a file even if it is\n\
                             inaccessible when tail starts or if it becomes\n\
                             inaccessible later -- useful only with -f\n\
  -c, --bytes=N            output the last N bytes\n\
  -f, --follow[={name|descriptor}] output appended data as the file grows;\n\
                             -f, --follow, and --follow=descriptor are\n\
                             equivalent\n\
  -n, --lines=N            output the last N lines, instead of the last %d\n\
      --max-unchanged-stats=N see the texinfo documentation\n\
                             (the default is %d)\n\
      --max-consecutive-size-changes=N see the texinfo documentation\n\
                             (the default is %d)\n\
      --pid=PID            with -f, terminate after process ID, PID dies\n\
  -q, --quiet, --silent    never output headers giving file names\n\
  -s, --sleep-interval=S   with -f, sleep S seconds between iterations\n\
  -v, --verbose            always output headers giving file names\n\
      --help               display this help and exit\n\
      --version            output version information and exit\n\
\n\
If the first character of N (the number of bytes or lines) is a `+',\n\
print beginning with the Nth item from the start of each file, otherwise,\n\
print the last N items in the file.  N may have a multiplier suffix:\n\
b for 512, k for 1024, m for 1048576 (1 Meg).  A first OPTION of -VALUE\n\
or +VALUE is treated like -n VALUE or -n +VALUE unless VALUE has one of\n\
the [bkm] suffix multipliers, in which case it is treated like -c VALUE\n\
or -c +VALUE.\n\
\n\
With --follow (-f), tail defaults to following the file descriptor, which\n\
means that even if a tail'ed file is renamed, tail will continue to track\n\
its end.  This default behavior is not desirable when you really want to\n\
track the actual name of the file, not the file descriptor (e.g., log\n\
rotation).  Use --follow=name in that case.  That causes tail to track the\n\
named file by reopening it periodically to see if it has been removed and\n\
recreated by some other program.\n\
\n", 180},
  {"closing %s (fd=%d)", 181},
  {"`%s' has become inaccessible", 182},
  {"\
`%s' has been replaced with a non-regular file;  cannot follow end of \
non-regular file", 183},
  {"`%s' has become accessible", 184},
  {"`%s' has appeared;  following end of new file", 185},
  {"`%s' has been replaced;  following end of new file", 186},
  {"file truncated", 187},
  {"no files remaining", 188},
  {"%s: cannot follow end of non-regular file", 189},
  {"%c: invalid suffix character in obsolescent option", 190},
  {"\
too many arguments;  When using tail's obsolescent option syntax (%s)\n\
there may be no more than one file argument.  Use the equivalent -n or -c\n\
option instead.", 191},
  {"\
Warning: it is not portable to use two or more file arguments with\n\
tail's obsolescent option syntax (%s).  Use the equivalent -n or -c\n\
option instead.", 192},
  {"%s: invalid maximum number of unchanged stats between opens", 193},
  {"%s: invalid maximum number of consecutive size changes", 194},
  {"%s: invalid PID", 195},
  {"%s: invalid number of seconds", 196},
  {"warning: --retry is useful only when following by name", 197},
  {"warning: PID ignored; --pid=PID is useful only when following", 198},
  {"Usage: %s [OPTION]... SET1 [SET2]\n", 199},
  {"\
Translate, squeeze, and/or delete characters from standard input,\n\
writing to standard output.\n\
\n\
  -c, --complement        first complement SET1\n\
  -d, --delete            delete characters in SET1, do not translate\n\
  -s, --squeeze-repeats   replace sequence of characters with one\n\
  -t, --truncate-set1     first truncate SET1 to length of SET2\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n", 200},
  {"\
\n\
SETs are specified as strings of characters.  Most represent themselves.\n\
Interpreted sequences are:\n\
\n\
  \\NNN            character with octal value NNN (1 to 3 octal digits)\n\
  \\\\              backslash\n\
  \\a              audible BEL\n\
  \\b              backspace\n\
  \\f              form feed\n\
  \\n              new line\n\
  \\r              return\n\
  \\t              horizontal tab\n\
  \\v              vertical tab\n\
  CHAR1-CHAR2     all characters from CHAR1 to CHAR2 in ascending order\n\
  [CHAR1-CHAR2]   same as CHAR1-CHAR2, if both SET1 and SET2 use this\n\
  [CHAR*]         in SET2, copies of CHAR until length of SET1\n\
  [CHAR*REPEAT]   REPEAT copies of CHAR, REPEAT octal if starting with 0\n\
  [:alnum:]       all letters and digits\n\
  [:alpha:]       all letters\n\
  [:blank:]       all horizontal whitespace\n\
  [:cntrl:]       all control characters\n\
  [:digit:]       all digits\n\
  [:graph:]       all printable characters, not including space\n\
  [:lower:]       all lower case letters\n\
  [:print:]       all printable characters, including space\n\
  [:punct:]       all punctuation characters\n\
  [:space:]       all horizontal or vertical whitespace\n\
  [:upper:]       all upper case letters\n\
  [:xdigit:]      all hexadecimal digits\n\
  [=CHAR=]        all characters which are equivalent to CHAR\n", 201},
  {"\
\n\
Translation occurs if -d is not given and both SET1 and SET2 appear.\n\
-t may be used only when translating.  SET2 is extended to length of\n\
SET1 by repeating its last character as necessary.  Excess characters\n\
of SET2 are ignored.  Only [:lower:] and [:upper:] are guaranteed to\n\
expand in ascending order; used in SET2 while translating, they may\n\
only be used in pairs to specify case conversion.  -s uses SET1 if not\n\
translating nor deleting; else squeezing uses SET2 and occurs after\n\
translation or deletion.\n", 202},
  {"\
warning: the ambiguous octal escape \\%c%c%c is being\n\
\tinterpreted as the 2-byte sequence \\0%c%c, `%c'", 203},
  {"invalid backslash escape at end of string", 204},
  {"invalid backslash escape `\\%c'", 205},
  {"range-endpoints of `%s-%s' are in reverse collating sequence order", 206},
  {"invalid repeat count `%s' in [c*n] construct", 207},
  {"invalid character class `%s'", 208},
  {"%s: equivalence class operand must be a single character", 209},
  {"the [c*] repeat construct may not appear in string1", 210},
  {"only one [c*] repeat construct may appear in string2", 211},
  {"[=c=] expressions may not appear in string2 when translating", 212},
  {"when not truncating set1, string2 must be non-empty", 213},
  {"\
when translating with complemented character classes,\n\
string2 must map all characters in the domain to one", 214},
  {"\
when translating, the only character classes that may appear in\n\
string2 are `upper' and `lower'", 215},
  {"the [c*] construct may appear in string2 only when translating", 216},
  {"two strings must be given when translating", 217},
  {"two strings must be given when both deleting and squeezing repeats", 218},
  {"only one string may be given when deleting without squeezing repeats", 219},
  {"at least one string must be given when squeezing repeats", 220},
  {"misaligned [:upper:] and/or [:lower:] construct", 221},
  {"\
invalid identity mapping;  when translating, any [:lower:] or [:upper:]\n\
construct in string1 must be aligned with a corresponding construct\n\
([:upper:] or [:lower:], respectively) in string2", 222},
  {"\
Usage: %s [OPTION] [FILE]\n\
Write totally ordered list consistent with the partial ordering in FILE.\n\
With no FILE, or when FILE is -, read standard input.\n\
\n\
      --help       display this help and exit\n\
      --version    output version information and exit\n", 223},
  {"\
\n\
Report bugs to <textutils-bugs@gnu.org>.", 224},
  {"%s: input contains a loop:\n", 225},
  {"could not find loop", 226},
  {"only one argument may be specified", 227},
  {"\
Convert spaces in each FILE to tabs, writing to standard output.\n\
With no FILE, or when FILE is -, read standard input.\n\
\n\
  -a, --all           convert all whitespace, instead of initial whitespace\n\
  -t, --tabs=NUMBER   have tabs NUMBER characters apart instead of 8\n\
  -t, --tabs=LIST     use comma separated list of explicit tab positions\n\
      --help          display this help and exit\n\
      --version       output version information and exit\n\
\n\
Instead of -t NUMBER or -t LIST, -NUMBER or -LIST may be used.\n", 228},
  {"Usage: %s [OPTION]... [INPUT [OUTPUT]]\n", 229},
  {"\
Discard all but one of successive identical lines from INPUT (or\n\
standard input), writing to OUTPUT (or standard output).\n\
\n\
  -c, --count           prefix lines by the number of occurrences\n\
  -d, --repeated        only print duplicate lines\n\
  -D, --all-repeated    print all duplicate lines\n\
  -f, --skip-fields=N   avoid comparing the first N fields\n\
  -i, --ignore-case     ignore differences in case when comparing\n\
  -s, --skip-chars=N    avoid comparing the first N characters\n\
  -u, --unique          only print unique lines\n\
  -w, --check-chars=N   compare no more than N characters in lines\n\
  -N                    same as -f N\n\
  +N                    same as -s N\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n\
\n\
A field is a run of whitespace, then non-whitespace characters.\n\
Fields are skipped before chars.\n", 230},
  {"error reading %s", 231},
  {"error writing %s", 232},
  {"invalid number of fields to skip: `%s'", 233},
  {"invalid number of bytes to skip: `%s'", 234},
  {"invalid number of bytes to compare: `%s'", 235},
  {"printing all duplicated lines and repeat counts is meaningless", 236},
  {"\
Print line, word, and byte counts for each FILE, and a total line if\n\
more than one FILE is specified.  With no FILE, or when FILE is -,\n\
read standard input.\n\
  -c, --bytes, --chars   print the byte counts\n\
  -l, --lines            print the newline counts\n\
  -L, --max-line-length  print the length of the longest line\n\
  -w, --words            print the word counts\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n", 237},
  {"total", 238},
};

int _msg_tbl_length = 238;
