GARNAME = autoconf
GARVERSION = 2.57
MASTER_SITES = ftp://ftp.gnu.org/pub/gnu/$(GARNAME)/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

BOOKS = $(WORKSRC)/doc/autoconf.texi
NODIST_BOOKS = $(WORKSRC)/doc/standards.texi

include ../../gar.mk

