TOP_DIR = ..
SUB_DIRS = \
	autoconf \
	automake \
	bash \
	binutils \
	bison \
	cvs \
	diffutils \
	findutils \
	flex \
	gawk \
	gcc \
	gdb \
	glibc \
	gpc \
	gperf \
	grep \
	libtool \
	m4 \
	make \
	readline \
	regex \
	sed \
	sh-utils \
	tar \
	textutils \
	which

include $(TOP_DIR)/rules.mak

